### ISSUE TITLE
AUTH_USER_MODEL issue

### ISSUE THREAD

**Issue by lithodidae** [codingforentrepreneurs/try-django-19#3]
Hi guys! see posts/models.py

user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)

The problem is, please refer to django1.9 docs, syntax for AUTH_USER_MODEL = 'myapp.MyUser' , which myapp is one of the app in INSTALLED_APPS and MyUser is Django model that use as User model, does that means you have to create a user model in Post app or create a new app such as user_profile containing user model??? So I'd rather choose a user model from django.contrib.auth until the new app and/or related models created.

Another problem is AUTH_USER_MODE not set from the beginning, If you intend to set AUTH_USER_MODEL, you better set it before creating any migrations or running manage.py migrate for the first time, otherwise, you will have dependency issues. see post/migrations 0002 and 0003

**Comment by codingforentrepreneurs** [comment]
Hello,

AUTH_USER_MODEL defaults to django's built-in User model. If you need to have a custom user model, then you'll set your own in your settings with something like AUTH_USER_MODEL = 'myuserapp.MyUserModel"

The foreign key to the AUTH_USER_MODEL is the best practice for associating the user model.

Does that make sense?
