### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by homepods** [codingforentrepreneurs/try-django-19#4]
Hi .. I am having trouble when I want to make a post - . After I press the button 'SAVE' I get an error .
The console looks like this - I'm using a pyodbc database - I have checked the 'id' is there.

Can anyone help me with this? 

`\posts\models.py", line 27, in upload_location
    new_id = PostModel.objects.order_by("id").last().id + 1
AttributeError: 'NoneType' object has no attribute 'id'
[25/Feb/2016 15:12:07] "POST /admin/posts/post/add/ HTTP/1.1" 500 187276
The thread 0x1040 has exited with code 0 (0x0).`

**Comment by codingforentrepreneurs** [comment]
Try this:

```
new_id = 1
qs = PostModel.objects.order_by("id").exists()
if qs:
      new_id = qs.last().id + 1
```

**Comment by MayurUp** [comment]
Hi,  I am having trouble when I want to make a second post. 

File "/posts/models.py", line 37, in upload_location
new_id = 1
qs = PostModel.objects.order_by("id").exists()
if qs:
    new_id = qs.last().id + 1
AttributeError: 'bool' object has no attribute 'last'

Can anyone help me with this?
